### ISSUE TITLE
Ошибка при создании прогона(TestRun)

### ISSUE THREAD

**Issue by EvgeniyShvetcov** [testit-tms/api-client-dotnet#27]
Доброго времени суток. Планируем использовать клиент для интеграции с GitLab. Сделал тестовый пример, для создания прогона через клиент, и столкнулся с ошибкой

> TestIT.ApiClient.Client.ApiException: Required property 'attachments' not found in JSON. Path '', line 1, position 481.
>    at TestIT.ApiClient.Client.CustomJsonCodec.Deserialize(HttpResponseMessage response, Type type)
>    at TestIT.ApiClient.Client.CustomJsonCodec.Deserialize[T](HttpResponseMessage response)
>    at TestIT.ApiClient.Client.ApiClient.ExecAsync[T](HttpRequestMessage req, IReadableConfiguration configuration, CancellationToken cancellationToken)

Код примерно следующий(Делал по примерам):
```       
 var tmsConfiguration = new Configuration()
{
    BasePath = "http://localhost",
};
tmsConfiguration.AddApiKeyPrefix("Authorization", "PrivateToken");
tmsConfiguration.AddApiKey("Authorization", "SomeToken");
var testRunsApi = new TestRunsApi(tmsConfiguration);
var request = new CreateEmptyRequest()
{
    ProjectId = Guid.NewGuid(),
    Name = "TestName",
};
try
{
    var response = testRunsApi.CreateEmpty(request);
}
catch (ApiException x)
{
    throw;
}
catch (Exception x)
{
    throw;
}
```
Я так понимаю, что клиент генерируется по OpenAPI схеме. Вытянул ту, с которой планируем интеграцию, и там немного отличается валидация моделей, в частности TestRunV2GetModel.
Можете подсказать, что следует сделать? Может необходимо обновить клиент или самим его сгенерировать?

**Comment by EvgeniyShvetcov** [comment]
Проблемы были с версиями библиотеки и API. Понизили версию и всё стало корректно)
